version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 54326:5432
    environment:
      POSTGRES_USER: vladimir
      POSTGRES_PASSWORD: 16fgh1986
      POSTGRES_DB: library
 # adminer:
  #  image: adminer:4.7.8-standalone
  #  restart: always
  #  ports:
   #   - 8080:8080
  backend:
    build:
      context: .
    privileged: true
    restart: always
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py create_data
      && gunicorn library.wsgi -b 0.0.0.0:8080
      "

    depends_on:
      - db
  nginx:
    build: ./nginx
    privileged: true
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    privileged: true
    ports:
      - 80:80
    depends_on:
      - nginx